# Generated by Django 5.2.7 on 2026-03-03 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='IngredientArrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество (приход)')),
                ('remaining_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Остаток в партии')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за единицу (₸)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата прихода')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='core.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Приход ингредиента',
                'verbose_name_plural': 'Приходы ингредиентов',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderWorkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Сделано штук')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='core.order', verbose_name='Заказ')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL, verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'Отчет о работе',
                'verbose_name_plural': 'Отчеты о работе',
            },
        ),
    ]
