# Generated by Django 5.2.7 on 2026-03-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ingredient_id_alter_order_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='На готовом складе (шт)'),
        ),
    ]
