# Generated by Django 5.2.7 on 2026-03-14 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('can_view_ready_stock', models.BooleanField(default=False, verbose_name='Готовый склад')),
                ('can_view_ingredients', models.BooleanField(default=False, verbose_name='Склад сырья')),
                ('can_view_arrivals', models.BooleanField(default=False, verbose_name='Приход')),
                ('can_view_cash', models.BooleanField(default=False, verbose_name='Касса')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Отчет')),
                ('can_view_staff', models.BooleanField(default=False, verbose_name='Сотрудники')),
                ('can_view_workers', models.BooleanField(default=False, verbose_name='Работники')),
                ('can_view_users', models.BooleanField(default=False, verbose_name='Пользователи')),
                ('can_view_categories', models.BooleanField(default=False, verbose_name='Категории')),
                ('can_view_products', models.BooleanField(default=False, verbose_name='Продукты')),
                ('can_view_wholesalers', models.BooleanField(default=False, verbose_name='Оптовики')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customrole', verbose_name='Индивидуальная роль'),
        ),
    ]
