# Generated by Django 5.2.7 on 2026-03-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customrole_user_custom_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrole',
            name='can_view_orders',
            field=models.BooleanField(default=False, verbose_name='Заказы'),
        ),
    ]
